### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by andya9** [mrichar1/clipster#42]
Running the latest git revision (dfa75b52ee3a41fff7534aca165dc0e6a24a3680). Python 3.6.

Since some days, when running `clipster -d` I get the following traceback:

```
Traceback (most recent call last):
  File "clipster", line 810, in <module>
    main()
  File "clipster", line 783, in main
    Daemon(config).run()
  File "clipster", line 639, in run
    self.prepare_files()
  File "clipster", line 580, in prepare_files
    os.kill(pid, 0)
PermissionError: [Errno 1] Operation not permitted
```

I tried googling for this error, and found [this](https://github.com/GNS3/gns3-gui/commit/d805cfbd6ac7fa6bf6a566c1ad2318f193954d8b)

**Comment by andya9** [comment]
After restarting, I'm not getting it anymore 😖
