### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by magnetophon** [mrichar1/clipster#44]
Thanks for the release!

On 1.0.0 I get the following error:
```
$ Traceback (most recent call last):
  File "/nix/store/vxwz45d3wqs1l28s7dax8vsfia9gvcx5-python3-3.5.3-env/lib/python3.5/site-packages/gi/overrides/GLib.py", line 735, in <lambda>
    func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
  File "/nix/store/8yclnhbfzz5xkgqsspdhkz3hf7qcqaid-clipster-1.0.0/bin/.clipster-wrapped", line 514, in socket_recv
    self.process_msg(conn)
  File "/nix/store/8yclnhbfzz5xkgqsspdhkz3hf7qcqaid-clipster-1.0.0/bin/.clipster-wrapped", line 544, in process_msg
    conn.sendall(json.dumps(self.boards[board][-count:][::-1]).encode('utf-8'))
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/nix/store/vxwz45d3wqs1l28s7dax8vsfia9gvcx5-python3-3.5.3-env/lib/python3.5/site-packages/gi/overrides/GLib.py", line 735, in <lambda>
    func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
  File "/nix/store/8yclnhbfzz5xkgqsspdhkz3hf7qcqaid-clipster-1.0.0/bin/.clipster-wrapped", line 514, in socket_recv
    self.process_msg(conn)
  File "/nix/store/8yclnhbfzz5xkgqsspdhkz3hf7qcqaid-clipster-1.0.0/bin/.clipster-wrapped", line 544, in process_msg
    conn.sendall(json.dumps(self.boards[board][-count:][::-1]).encode('utf-8'))
BrokenPipeError: [Errno 32] Broken pipe
 Traceback (most recent call last):
  File "/nix/store/vxwz45d3wqs1l28s7dax8vsfia9gvcx5-python3-3.5.3-env/lib/python3.5/site-packages/gi/overrides/GLib.py", line 735, in <lambda>
    func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
  File "/nix/store/8yclnhbfzz5xkgqsspdhkz3hf7qcqaid-clipster-1.0.0/bin/.clipster-wrapped", line 514, in socket_recv
    self.process_msg(conn)
  File "/nix/store/8yclnhbfzz5xkgqsspdhkz3hf7qcqaid-clipster-1.0.0/bin/.clipster-wrapped", line 544, in process_msg
```

**Comment by mrichar1** [comment]
Hi,

Thanks for reporting this! There haven't really been any code changes between the 1.0.0 release and the previous untagged master, so I'm not sure if this is a side-effect of packaging, or if you were just using an older version from master and one of the other commits since then has caused this to occur.

Can you let me know if this error is coming from the client, or the server? And please run both with `-lDEBUG` and append those results too. Thanks!

**Comment by magnetophon** [comment]
This might have been there for a longer time; I just didn't notice, cause I don't usually start clipster from the cli.

This is coming from the server: `clipster -d -lDEBUG`.
I get what looks like normal debug output, but when I run
`clipster -o -n 0 -0 | rofi -i -dmenu -sep '\x00' -eh 2 -p paste: | tr -d '\n' | clipster`
for the second time, I get:
``
Traceback (most recent call last):
  File "/nix/store/vxwz45d3wqs1l28s7dax8vsfia9gvcx5-python3-3.5.3-env/lib/python3.5/site-packages/gi/overrides/GLib.py", line 735, in <lambda>
    func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
  File "/nix/store/8yclnhbfzz5xkgqsspdhkz3hf7qcqaid-clipster-1.0.0/bin/.clipster-wrapped", line 514, in socket_recv
    self.process_msg(conn)
  File "/nix/store/8yclnhbfzz5xkgqsspdhkz3hf7qcqaid-clipster-1.0.0/bin/.clipster-wrapped", line 544, in process_msg
    conn.sendall(json.dumps(self.boards[board][-count:][::-1]).encode('utf-8'))
BrokenPipeError: [Errno 32] Broken pipe
``

**Comment by mrichar1** [comment]
Thanks for this extra info!

So it turned out that you were triggering an uncommon corner case with your pipes, where STDIN being passed to the final clipster command was empty - the equivalent of running e.g. `/bin/true | clipster`

The message protocol being used was ambiguous, so the server was trying to return the latest clipboard items, even though the client wasn't expecting them, and had hung up (hence the broken pipe).

I've changed the protocol to differentiate between no content and empty content, and behave accordingly.  I've also added handling for socket errors on the server, since these can probably be triggered in a number of ways.

Now released a (hopefully!) working version tagged as `1.0.1`

Please let me know if this fixes your problems! (There may still be a problem with the final clipster in your command chain receiving empty data, but that's probably a separate issue...)

**Comment by magnetophon** [comment]
Seems to be fixed now. Thanks!
